### ISSUE TITLE
Mergify should merge scala steward PR automatically if CI success

### ISSUE THREAD

**Issue by dylandoamaral** [univalence/zio-spark#23]
There is a problem with the mergify rule, normally it should merge the PR of scala steward automatically. However he can't since the Circle ci build in github actions is not enable for scala steward's PR.

**Comment by ahoy-jon** [comment]
How can we solve that? Is there a solution?

**Comment by dylandoamaral** [comment]
I don't why CircleCI is not acting correctly with scala steward PR :/.

**Comment by dylandoamaral** [comment]
I enabled something named: `Pass secrets to builds from forked pull requests` in CircleCI hope it will fix the issue !

**Comment by dylandoamaral** [comment]
Just be sure that there is no security issues with your build configuration :).
