### ISSUE TITLE
support for the broadcast API

### ISSUE THREAD

**Issue by ahoy-jon** [univalence/zio-spark#286]
When working on #285, the broadcast API was missing.

Current workaround:
```scala
val makeBroadcast = zio.spark.sql.SparkSession.attempt(_.sparkContext.broadcast(ids))
```

**Comment by dylandoamaral** [comment]
To make it close to the actual Spark API, I will have to wrap the entire sparkContext object.

**Comment by ahoy-jon** [comment]
Ouch, that's huge.
Do it, I guess .... 😬🙏
